### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by FluffyDiscord** [SanityCh3ck/horse-stonks#1]
First try, got horse, which has lower jump AND speed.

**Comment by SanityCh3ck** [comment]
That's strange, I'm using it on my own server without problems.

Are you using it in singleplayer or multiplayer, and what other mods do you have?

**Comment by FluffyDiscord** [comment]
Singleplayer. Try the All of fabric 4 0.0.4 with your mod. Your mod may be overwritten by some other mod I guess.

**Comment by SanityCh3ck** [comment]
What were the stats of both parents, and the stats of the child?

For example, if parent A has 13 hearts and parent B has 11 hearts, the child should always have at least 11 hearts. In vanilla, you could get offspring with less than 11 hearts.

**Comment by FluffyDiscord** [comment]
ah, I guess that does work. Sorry my bad
