### ISSUE TITLE
Is there a limit to horse stats?

### ISSUE THREAD

**Issue by satoon10** [SanityCh3ck/horse-stonks#5]
Does this mean if I keep breeding horses they'll go faster and faster, or is there a limit?

**Comment by SanityCh3ck** [comment]
Sorry for the late reply.
This mod uses the vanilla breeding logic, and if the result of that is worse than the worst parent, it uses the value from the worst parent instead. All of the vanilla limits still apply.

For example, if parent A has 11 hearts and parent B has 12 hearts, all children will have at least 11 hearts.
