### ISSUE TITLE
Crash when destroying a minecart with horse stonks installed

### ISSUE THREAD

**Issue by BLUEChester** [SanityCh3ck/horse-stonks#6]
Minecraft version: 1.19.2
Modloader: Fabric (Quilt)
Fabric loader version: 0.18.10
Environment: Singleplayer

Whenever I destroyed a minecart the mod crashes my game, this happened consistently, and every single time I destroy a minecart. The reason I believe it is the horse stonks mod causing it is that I tried removing all my mods from the game and after removing this mod the issue was resolved.

Edit: After more testing, I believe it could be a compatibility issue with [Double Doors](https://modrinth.com/mod/double-doors) as removing either double doors or horse stonks resolved the issue.

Thanks heaps for your work on this mod! 

Crash report
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/11358823/latest.log)

[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/11358825/debug.log)

**Comment by SanityCh3ck** [comment]
That is super weird. My mod doesn't touch anything that doesn't have to do with horse breeding.

Does this problem exist on Forge, Fabric or Quilt? Your latest.log is from a Quilt instance, and the debug.log is from a Forge instance.

Have you tried it with *only* Double Doors and Horse Stonks installed?

I did a quick test on both Forge and Quilt for MC 1.19.2, with only Double Doors and Horse Stonks, and wasn't able to reproduce the issue.
